### PR TITLE
add listener name setting

### PR DESCRIPTION
**Pull request by dlwr**
@uiureo 
I added listener name setting, to know 'WHO' playing a song, as follows.

thanks, regards.

### CODE REVIEW

**Comment by uiur** [comment]
Looks good to me. Thanks :+1:

**Comment by uiur** [comment]
@dlwr 
Sorry for delay.
It has been released under [v1.1.0](https://github.com/uiureo/playing/releases/tag/v1.1.0) :tada:

**Comment by dlwr** [comment]
@uiureo SO sorry for forgotting replying for a long time...:astonished: and thanks very much to bump up version!

**Comment by uiur** [comment]
:v:

**Pull request merged**
